// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SaveFileIO","status":true,"description":"Adds download/upload options to the save and load screens.","parameters":{}}
];
